"""added cascade delete

Revision ID: 0ed2f44f15cb
Revises: 977e3c064a91
Create Date: 2026-06-19 23:31:14.072881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed2f44f15cb'
down_revision: Union[str, None] = '977e3c064a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_place_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('person_events_person_id_fkey', 'person_events', type_='foreignkey')
    op.drop_constraint('person_events_event_id_fkey', 'person_events', type_='foreignkey')
    op.create_foreign_key(None, 'person_events', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'person_events', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('person_relations_person_id_fkey', 'person_relations', type_='foreignkey')
    op.drop_constraint('person_relations_related_person_id_fkey', 'person_relations', type_='foreignkey')
    op.create_foreign_key(None, 'person_relations', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'person_relations', 'persons', ['related_person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('persons_place_id_fkey', 'persons', type_='foreignkey')
    op.drop_constraint('persons_birth_place_id_fkey', 'persons', type_='foreignkey')
    op.drop_constraint('persons_family_id_fkey', 'persons', type_='foreignkey')
    op.drop_constraint('persons_death_place_id_fkey', 'persons', type_='foreignkey')
    op.create_foreign_key(None, 'persons', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'persons', 'families', ['family_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'persons', 'places', ['death_place_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'persons', 'places', ['birth_place_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('places_parent_id_fkey', 'places', type_='foreignkey')
    op.create_foreign_key(None, 'places', 'places', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.create_foreign_key('places_parent_id_fkey', 'places', 'places', ['parent_id'], ['id'])
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.create_foreign_key('persons_death_place_id_fkey', 'persons', 'places', ['death_place_id'], ['id'])
    op.create_foreign_key('persons_family_id_fkey', 'persons', 'families', ['family_id'], ['id'])
    op.create_foreign_key('persons_birth_place_id_fkey', 'persons', 'places', ['birth_place_id'], ['id'])
    op.create_foreign_key('persons_place_id_fkey', 'persons', 'places', ['place_id'], ['id'])
    op.drop_constraint(None, 'person_relations', type_='foreignkey')
    op.drop_constraint(None, 'person_relations', type_='foreignkey')
    op.create_foreign_key('person_relations_related_person_id_fkey', 'person_relations', 'persons', ['related_person_id'], ['id'])
    op.create_foreign_key('person_relations_person_id_fkey', 'person_relations', 'persons', ['person_id'], ['id'])
    op.drop_constraint(None, 'person_events', type_='foreignkey')
    op.drop_constraint(None, 'person_events', type_='foreignkey')
    op.create_foreign_key('person_events_event_id_fkey', 'person_events', 'events', ['event_id'], ['id'])
    op.create_foreign_key('person_events_person_id_fkey', 'person_events', 'persons', ['person_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_place_id_fkey', 'events', 'places', ['place_id'], ['id'])
    # ### end Alembic commands ###
