"""добавил поттверждение кодов через почту

Revision ID: 63d9dd7f58d1
Revises: a6ced910aabd
Create Date: 2026-07-03 00:17:52.652884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d9dd7f58d1'
down_revision: Union[str, None] = 'a6ced910aabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirm_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirm_codes_email'), 'confirm_codes', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirm_codes_email'), table_name='confirm_codes')
    op.drop_table('confirm_codes')
    # ### end Alembic commands ###
