"""empty message

Revision ID: 6d2b68b48507
Revises: 0ed2f44f15cb
Create Date: 2026-06-20 16:12:41.881595

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6d2b68b48507'
down_revision: Union[str, None] = '0ed2f44f15cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
