"""add person_id to events

Revision ID: 71274bcb041d
Revises: ac0cf30e07bb
Create Date: 2026-06-23 20:47:02.949595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71274bcb041d'
down_revision: Union[str, None] = 'ac0cf30e07bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('person_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'events', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'person_id')
    # ### end Alembic commands ###
