"""empty message

Revision ID: a328a41a9557
Revises: a37d239b5409
Create Date: 2026-06-15 21:38:54.781192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a328a41a9557'
down_revision: Union[str, None] = 'a37d239b5409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('persons', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('persons', 'biography',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'biography',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('persons', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('events', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
