"""исправил ошибку с стандартными значениями

Revision ID: a6ced910aabd
Revises: c1715d6aca0b
Create Date: 2026-07-01 17:59:17.545773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ced910aabd'
down_revision: Union[str, None] = 'c1715d6aca0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tokens', ['id'])
    op.add_column('users', sa.Column('elua', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_confirm', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('can_invite', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'can_invite')
    op.drop_column('users', 'email_confirm')
    op.drop_column('users', 'elua')
    op.drop_constraint(None, 'tokens', type_='unique')
    # ### end Alembic commands ###
