"""empty message

Revision ID: e7632effc48d
Revises: a328a41a9557
Create Date: 2026-06-16 01:04:36.969111

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'e7632effc48d'
down_revision: Union[str, None] = 'a328a41a9557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
