server {
    listen 80;
    server_name "Family Tree Server";

    client_max_body_size 512m;

    root /usr/share/nginx/html;
    index index.html;


    location /photos/ {
        alias /var/photos/;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
