server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Раздача фото
    location /photos/ {
        alias /var/photos/;
    }

    # SPA fallback — все запросы, не ведущие к реальному файлу, отдают index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проксирование API
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
